/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 15
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_DOT = 2,
  anon_sym_safe = 3,
  anon_sym_async = 4,
  anon_sym_sensitive = 5,
  anon_sym_BANGsensitive_BANG = 6,
  anon_sym_elevated = 7,
  anon_sym_if = 8,
  anon_sym_else = 9,
  anon_sym_end = 10,
  anon_sym_repeat = 11,
  anon_sym_while = 12,
  anon_sym_success = 13,
  anon_sym_failure = 14,
  anon_sym_increase = 15,
  anon_sym_decrease = 16,
  anon_sym_is = 17,
  anon_sym_as = 18,
  anon_sym_into = 19,
  anon_sym_with = 20,
  anon_sym_without = 21,
  anon_sym_trace = 22,
  anon_sym_elapsed = 23,
  anon_sym_timeout = 24,
  anon_sym_silent = 25,
  anon_sym_on = 26,
  sym_variable_scalar = 27,
  sym_variable_container = 28,
  sym_variable_projection = 29,
  sym_string = 30,
  sym_number = 31,
  anon_sym_true = 32,
  anon_sym_false = 33,
  sym_identifier = 34,
  sym_source_file = 35,
  sym__statement = 36,
  sym_command_line = 37,
  sym_clause = 38,
  sym__token = 39,
  sym_control_keyword = 40,
  sym_clause_keyword = 41,
  sym_signature_keyword = 42,
  sym_boolean = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_command_line_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_DOT] = ".",
  [anon_sym_safe] = "safe",
  [anon_sym_async] = "async",
  [anon_sym_sensitive] = "sensitive",
  [anon_sym_BANGsensitive_BANG] = "(!)sensitive",
  [anon_sym_elevated] = "elevated",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_end] = "end",
  [anon_sym_repeat] = "repeat",
  [anon_sym_while] = "while",
  [anon_sym_success] = "success",
  [anon_sym_failure] = "failure",
  [anon_sym_increase] = "increase",
  [anon_sym_decrease] = "decrease",
  [anon_sym_is] = "is",
  [anon_sym_as] = "as",
  [anon_sym_into] = "into",
  [anon_sym_with] = "with",
  [anon_sym_without] = "without",
  [anon_sym_trace] = "trace",
  [anon_sym_elapsed] = "elapsed",
  [anon_sym_timeout] = "timeout",
  [anon_sym_silent] = "silent",
  [anon_sym_on] = "on",
  [sym_variable_scalar] = "variable_scalar",
  [sym_variable_container] = "variable_container",
  [sym_variable_projection] = "variable_projection",
  [sym_string] = "string",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_command_line] = "command_line",
  [sym_clause] = "clause",
  [sym__token] = "_token",
  [sym_control_keyword] = "control_keyword",
  [sym_clause_keyword] = "clause_keyword",
  [sym_signature_keyword] = "signature_keyword",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_command_line_repeat1] = "command_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_safe] = anon_sym_safe,
  [anon_sym_async] = anon_sym_async,
  [anon_sym_sensitive] = anon_sym_sensitive,
  [anon_sym_BANGsensitive_BANG] = anon_sym_BANGsensitive_BANG,
  [anon_sym_elevated] = anon_sym_elevated,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_repeat] = anon_sym_repeat,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_success] = anon_sym_success,
  [anon_sym_failure] = anon_sym_failure,
  [anon_sym_increase] = anon_sym_increase,
  [anon_sym_decrease] = anon_sym_decrease,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_into] = anon_sym_into,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_without] = anon_sym_without,
  [anon_sym_trace] = anon_sym_trace,
  [anon_sym_elapsed] = anon_sym_elapsed,
  [anon_sym_timeout] = anon_sym_timeout,
  [anon_sym_silent] = anon_sym_silent,
  [anon_sym_on] = anon_sym_on,
  [sym_variable_scalar] = sym_variable_scalar,
  [sym_variable_container] = sym_variable_container,
  [sym_variable_projection] = sym_variable_projection,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_command_line] = sym_command_line,
  [sym_clause] = sym_clause,
  [sym__token] = sym__token,
  [sym_control_keyword] = sym_control_keyword,
  [sym_clause_keyword] = sym_clause_keyword,
  [sym_signature_keyword] = sym_signature_keyword,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_command_line_repeat1] = aux_sym_command_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_safe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_async] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sensitive] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANGsensitive_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elevated] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_repeat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_success] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_failure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_increase] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_decrease] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_into] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_without] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elapsed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_timeout] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_silent] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = false,
  },
  [sym_variable_scalar] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_container] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_projection] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_command_line] = {
    .visible = true,
    .named = true,
  },
  [sym_clause] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_control_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_clause_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_signature_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '!', 5,
        '\'', 3,
        '.', 21,
        ':', 6,
        '@', 16,
        'a', 120,
        'd', 73,
        'e', 103,
        'f', 55,
        'i', 93,
        'o', 109,
        'r', 74,
        's', 56,
        't', 98,
        'w', 95,
        '~', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(25);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 4,
        '\'', 3,
        '.', 21,
        ':', 6,
        '@', 16,
        'a', 122,
        'd', 73,
        'e', 105,
        'f', 55,
        'i', 93,
        'o', 109,
        'r', 74,
        's', 97,
        't', 98,
        'w', 95,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(50);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == '@') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == '@') ADVANCE(16);
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(1);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'v') ADVANCE(8);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 16:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 17:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 18:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_safe);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_async);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_sensitive);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_BANGsensitive_BANG);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_elevated);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_end);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_repeat);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_while);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_success);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_failure);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_increase);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_decrease);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_is);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_as);
      if (lookahead == 'y') ADVANCE(111);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_as);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_into);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_with);
      if (lookahead == 'o') ADVANCE(137);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_without);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_trace);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_elapsed);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_timeout);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_silent);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_on);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_variable_scalar);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_variable_container);
      if (lookahead == ':') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_variable_container);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(99);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(94);
      if (lookahead == 'e') ADVANCE(110);
      if (lookahead == 'i') ADVANCE(106);
      if (lookahead == 'u') ADVANCE(66);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(116);
      if (lookahead == 'e') ADVANCE(139);
      if (lookahead == 's') ADVANCE(75);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(116);
      if (lookahead == 's') ADVANCE(75);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(135);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(130);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(68);
      if (lookahead == 'u') ADVANCE(77);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(127);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(128);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(117);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(23);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(67);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(89);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(79);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(119);
      if (lookahead == 't') ADVANCE(113);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(29);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(26);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(115);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(53);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(42);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(33);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(34);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(71);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(114);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(62);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(72);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(124);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(112);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(27);
      if (lookahead == 'n') ADVANCE(69);
      if (lookahead == 's') ADVANCE(36);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(76);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(102);
      if (lookahead == 'i') ADVANCE(129);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(40);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(106);
      if (lookahead == 'u') ADVANCE(66);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(108);
      if (lookahead == 'r') ADVANCE(61);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(104);
      if (lookahead == 'l') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(140);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(134);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(107);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(57);
      if (lookahead == 'n') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(138);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(58);
      if (lookahead == 'n') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(90);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(46);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(123);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(131);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(39);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(136);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(91);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(126);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(81);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(92);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(37);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(32);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(101);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(121);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(78);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(85);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(82);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(83);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(96);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(30);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(45);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(44);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(100);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(132);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(133);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(118);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(59);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(84);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(141);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_safe] = ACTIONS(1),
    [anon_sym_async] = ACTIONS(1),
    [anon_sym_sensitive] = ACTIONS(1),
    [anon_sym_BANGsensitive_BANG] = ACTIONS(1),
    [anon_sym_elevated] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_repeat] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_success] = ACTIONS(1),
    [anon_sym_failure] = ACTIONS(1),
    [anon_sym_increase] = ACTIONS(1),
    [anon_sym_decrease] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_into] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_without] = ACTIONS(1),
    [anon_sym_trace] = ACTIONS(1),
    [anon_sym_elapsed] = ACTIONS(1),
    [anon_sym_timeout] = ACTIONS(1),
    [anon_sym_silent] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [sym_variable_scalar] = ACTIONS(1),
    [sym_variable_container] = ACTIONS(1),
    [sym_variable_projection] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym__statement] = STATE(2),
    [sym_command_line] = STATE(2),
    [sym_clause] = STATE(9),
    [sym__token] = STATE(4),
    [sym_control_keyword] = STATE(4),
    [sym_clause_keyword] = STATE(4),
    [sym_signature_keyword] = STATE(4),
    [sym_boolean] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_command_line_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_safe] = ACTIONS(7),
    [anon_sym_async] = ACTIONS(7),
    [anon_sym_sensitive] = ACTIONS(7),
    [anon_sym_BANGsensitive_BANG] = ACTIONS(9),
    [anon_sym_elevated] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_else] = ACTIONS(11),
    [anon_sym_end] = ACTIONS(11),
    [anon_sym_repeat] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_success] = ACTIONS(11),
    [anon_sym_failure] = ACTIONS(11),
    [anon_sym_increase] = ACTIONS(11),
    [anon_sym_decrease] = ACTIONS(11),
    [anon_sym_is] = ACTIONS(13),
    [anon_sym_as] = ACTIONS(13),
    [anon_sym_into] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_without] = ACTIONS(13),
    [anon_sym_trace] = ACTIONS(15),
    [anon_sym_elapsed] = ACTIONS(15),
    [anon_sym_timeout] = ACTIONS(15),
    [anon_sym_silent] = ACTIONS(15),
    [anon_sym_on] = ACTIONS(15),
    [sym_variable_scalar] = ACTIONS(17),
    [sym_variable_container] = ACTIONS(17),
    [sym_variable_projection] = ACTIONS(19),
    [sym_string] = ACTIONS(17),
    [sym_number] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_identifier] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(3),
    [sym_command_line] = STATE(3),
    [sym_clause] = STATE(9),
    [sym__token] = STATE(4),
    [sym_control_keyword] = STATE(4),
    [sym_clause_keyword] = STATE(4),
    [sym_signature_keyword] = STATE(4),
    [sym_boolean] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_command_line_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_comment] = ACTIONS(25),
    [anon_sym_safe] = ACTIONS(7),
    [anon_sym_async] = ACTIONS(7),
    [anon_sym_sensitive] = ACTIONS(7),
    [anon_sym_BANGsensitive_BANG] = ACTIONS(9),
    [anon_sym_elevated] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_else] = ACTIONS(11),
    [anon_sym_end] = ACTIONS(11),
    [anon_sym_repeat] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_success] = ACTIONS(11),
    [anon_sym_failure] = ACTIONS(11),
    [anon_sym_increase] = ACTIONS(11),
    [anon_sym_decrease] = ACTIONS(11),
    [anon_sym_is] = ACTIONS(13),
    [anon_sym_as] = ACTIONS(13),
    [anon_sym_into] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_without] = ACTIONS(13),
    [anon_sym_trace] = ACTIONS(15),
    [anon_sym_elapsed] = ACTIONS(15),
    [anon_sym_timeout] = ACTIONS(15),
    [anon_sym_silent] = ACTIONS(15),
    [anon_sym_on] = ACTIONS(15),
    [sym_variable_scalar] = ACTIONS(17),
    [sym_variable_container] = ACTIONS(17),
    [sym_variable_projection] = ACTIONS(19),
    [sym_string] = ACTIONS(17),
    [sym_number] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_identifier] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(3),
    [sym_command_line] = STATE(3),
    [sym_clause] = STATE(9),
    [sym__token] = STATE(4),
    [sym_control_keyword] = STATE(4),
    [sym_clause_keyword] = STATE(4),
    [sym_signature_keyword] = STATE(4),
    [sym_boolean] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_command_line_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_comment] = ACTIONS(29),
    [anon_sym_safe] = ACTIONS(32),
    [anon_sym_async] = ACTIONS(32),
    [anon_sym_sensitive] = ACTIONS(32),
    [anon_sym_BANGsensitive_BANG] = ACTIONS(35),
    [anon_sym_elevated] = ACTIONS(32),
    [anon_sym_if] = ACTIONS(38),
    [anon_sym_else] = ACTIONS(38),
    [anon_sym_end] = ACTIONS(38),
    [anon_sym_repeat] = ACTIONS(38),
    [anon_sym_while] = ACTIONS(38),
    [anon_sym_success] = ACTIONS(38),
    [anon_sym_failure] = ACTIONS(38),
    [anon_sym_increase] = ACTIONS(38),
    [anon_sym_decrease] = ACTIONS(38),
    [anon_sym_is] = ACTIONS(41),
    [anon_sym_as] = ACTIONS(41),
    [anon_sym_into] = ACTIONS(41),
    [anon_sym_with] = ACTIONS(41),
    [anon_sym_without] = ACTIONS(41),
    [anon_sym_trace] = ACTIONS(44),
    [anon_sym_elapsed] = ACTIONS(44),
    [anon_sym_timeout] = ACTIONS(44),
    [anon_sym_silent] = ACTIONS(44),
    [anon_sym_on] = ACTIONS(44),
    [sym_variable_scalar] = ACTIONS(47),
    [sym_variable_container] = ACTIONS(47),
    [sym_variable_projection] = ACTIONS(50),
    [sym_string] = ACTIONS(47),
    [sym_number] = ACTIONS(47),
    [anon_sym_true] = ACTIONS(53),
    [anon_sym_false] = ACTIONS(53),
    [sym_identifier] = ACTIONS(50),
  },
  [STATE(4)] = {
    [sym__token] = STATE(7),
    [sym_control_keyword] = STATE(7),
    [sym_clause_keyword] = STATE(7),
    [sym_signature_keyword] = STATE(7),
    [sym_boolean] = STATE(7),
    [aux_sym_command_line_repeat1] = STATE(7),
    [anon_sym_DOT] = ACTIONS(56),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_else] = ACTIONS(11),
    [anon_sym_end] = ACTIONS(11),
    [anon_sym_repeat] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_success] = ACTIONS(11),
    [anon_sym_failure] = ACTIONS(11),
    [anon_sym_increase] = ACTIONS(11),
    [anon_sym_decrease] = ACTIONS(11),
    [anon_sym_is] = ACTIONS(13),
    [anon_sym_as] = ACTIONS(13),
    [anon_sym_into] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_without] = ACTIONS(13),
    [anon_sym_trace] = ACTIONS(15),
    [anon_sym_elapsed] = ACTIONS(15),
    [anon_sym_timeout] = ACTIONS(15),
    [anon_sym_silent] = ACTIONS(15),
    [anon_sym_on] = ACTIONS(15),
    [sym_variable_scalar] = ACTIONS(58),
    [sym_variable_container] = ACTIONS(58),
    [sym_variable_projection] = ACTIONS(60),
    [sym_string] = ACTIONS(58),
    [sym_number] = ACTIONS(58),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_identifier] = ACTIONS(60),
  },
  [STATE(5)] = {
    [sym__token] = STATE(7),
    [sym_control_keyword] = STATE(7),
    [sym_clause_keyword] = STATE(7),
    [sym_signature_keyword] = STATE(7),
    [sym_boolean] = STATE(7),
    [aux_sym_command_line_repeat1] = STATE(7),
    [anon_sym_DOT] = ACTIONS(62),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_else] = ACTIONS(11),
    [anon_sym_end] = ACTIONS(11),
    [anon_sym_repeat] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_success] = ACTIONS(11),
    [anon_sym_failure] = ACTIONS(11),
    [anon_sym_increase] = ACTIONS(11),
    [anon_sym_decrease] = ACTIONS(11),
    [anon_sym_is] = ACTIONS(13),
    [anon_sym_as] = ACTIONS(13),
    [anon_sym_into] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_without] = ACTIONS(13),
    [anon_sym_trace] = ACTIONS(15),
    [anon_sym_elapsed] = ACTIONS(15),
    [anon_sym_timeout] = ACTIONS(15),
    [anon_sym_silent] = ACTIONS(15),
    [anon_sym_on] = ACTIONS(15),
    [sym_variable_scalar] = ACTIONS(58),
    [sym_variable_container] = ACTIONS(58),
    [sym_variable_projection] = ACTIONS(60),
    [sym_string] = ACTIONS(58),
    [sym_number] = ACTIONS(58),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_identifier] = ACTIONS(60),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(64),
    [sym_comment] = ACTIONS(64),
    [anon_sym_safe] = ACTIONS(66),
    [anon_sym_async] = ACTIONS(66),
    [anon_sym_sensitive] = ACTIONS(66),
    [anon_sym_BANGsensitive_BANG] = ACTIONS(64),
    [anon_sym_elevated] = ACTIONS(66),
    [anon_sym_if] = ACTIONS(66),
    [anon_sym_else] = ACTIONS(66),
    [anon_sym_end] = ACTIONS(66),
    [anon_sym_repeat] = ACTIONS(66),
    [anon_sym_while] = ACTIONS(66),
    [anon_sym_success] = ACTIONS(66),
    [anon_sym_failure] = ACTIONS(66),
    [anon_sym_increase] = ACTIONS(66),
    [anon_sym_decrease] = ACTIONS(66),
    [anon_sym_is] = ACTIONS(66),
    [anon_sym_as] = ACTIONS(66),
    [anon_sym_into] = ACTIONS(66),
    [anon_sym_with] = ACTIONS(66),
    [anon_sym_without] = ACTIONS(66),
    [anon_sym_trace] = ACTIONS(66),
    [anon_sym_elapsed] = ACTIONS(66),
    [anon_sym_timeout] = ACTIONS(66),
    [anon_sym_silent] = ACTIONS(66),
    [anon_sym_on] = ACTIONS(66),
    [sym_variable_scalar] = ACTIONS(64),
    [sym_variable_container] = ACTIONS(64),
    [sym_variable_projection] = ACTIONS(66),
    [sym_string] = ACTIONS(64),
    [sym_number] = ACTIONS(64),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_identifier] = ACTIONS(66),
  },
  [STATE(7)] = {
    [sym__token] = STATE(7),
    [sym_control_keyword] = STATE(7),
    [sym_clause_keyword] = STATE(7),
    [sym_signature_keyword] = STATE(7),
    [sym_boolean] = STATE(7),
    [aux_sym_command_line_repeat1] = STATE(7),
    [anon_sym_DOT] = ACTIONS(68),
    [anon_sym_if] = ACTIONS(70),
    [anon_sym_else] = ACTIONS(70),
    [anon_sym_end] = ACTIONS(70),
    [anon_sym_repeat] = ACTIONS(70),
    [anon_sym_while] = ACTIONS(70),
    [anon_sym_success] = ACTIONS(70),
    [anon_sym_failure] = ACTIONS(70),
    [anon_sym_increase] = ACTIONS(70),
    [anon_sym_decrease] = ACTIONS(70),
    [anon_sym_is] = ACTIONS(73),
    [anon_sym_as] = ACTIONS(73),
    [anon_sym_into] = ACTIONS(73),
    [anon_sym_with] = ACTIONS(73),
    [anon_sym_without] = ACTIONS(73),
    [anon_sym_trace] = ACTIONS(76),
    [anon_sym_elapsed] = ACTIONS(76),
    [anon_sym_timeout] = ACTIONS(76),
    [anon_sym_silent] = ACTIONS(76),
    [anon_sym_on] = ACTIONS(76),
    [sym_variable_scalar] = ACTIONS(79),
    [sym_variable_container] = ACTIONS(79),
    [sym_variable_projection] = ACTIONS(82),
    [sym_string] = ACTIONS(79),
    [sym_number] = ACTIONS(79),
    [anon_sym_true] = ACTIONS(85),
    [anon_sym_false] = ACTIONS(85),
    [sym_identifier] = ACTIONS(82),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(88),
    [sym_comment] = ACTIONS(88),
    [anon_sym_safe] = ACTIONS(90),
    [anon_sym_async] = ACTIONS(90),
    [anon_sym_sensitive] = ACTIONS(90),
    [anon_sym_BANGsensitive_BANG] = ACTIONS(88),
    [anon_sym_elevated] = ACTIONS(90),
    [anon_sym_if] = ACTIONS(90),
    [anon_sym_else] = ACTIONS(90),
    [anon_sym_end] = ACTIONS(90),
    [anon_sym_repeat] = ACTIONS(90),
    [anon_sym_while] = ACTIONS(90),
    [anon_sym_success] = ACTIONS(90),
    [anon_sym_failure] = ACTIONS(90),
    [anon_sym_increase] = ACTIONS(90),
    [anon_sym_decrease] = ACTIONS(90),
    [anon_sym_is] = ACTIONS(90),
    [anon_sym_as] = ACTIONS(90),
    [anon_sym_into] = ACTIONS(90),
    [anon_sym_with] = ACTIONS(90),
    [anon_sym_without] = ACTIONS(90),
    [anon_sym_trace] = ACTIONS(90),
    [anon_sym_elapsed] = ACTIONS(90),
    [anon_sym_timeout] = ACTIONS(90),
    [anon_sym_silent] = ACTIONS(90),
    [anon_sym_on] = ACTIONS(90),
    [sym_variable_scalar] = ACTIONS(88),
    [sym_variable_container] = ACTIONS(88),
    [sym_variable_projection] = ACTIONS(90),
    [sym_string] = ACTIONS(88),
    [sym_number] = ACTIONS(88),
    [anon_sym_true] = ACTIONS(90),
    [anon_sym_false] = ACTIONS(90),
    [sym_identifier] = ACTIONS(90),
  },
  [STATE(9)] = {
    [sym__token] = STATE(5),
    [sym_control_keyword] = STATE(5),
    [sym_clause_keyword] = STATE(5),
    [sym_signature_keyword] = STATE(5),
    [sym_boolean] = STATE(5),
    [aux_sym_command_line_repeat1] = STATE(5),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_else] = ACTIONS(11),
    [anon_sym_end] = ACTIONS(11),
    [anon_sym_repeat] = ACTIONS(11),
    [anon_sym_while] = ACTIONS(11),
    [anon_sym_success] = ACTIONS(11),
    [anon_sym_failure] = ACTIONS(11),
    [anon_sym_increase] = ACTIONS(11),
    [anon_sym_decrease] = ACTIONS(11),
    [anon_sym_is] = ACTIONS(13),
    [anon_sym_as] = ACTIONS(13),
    [anon_sym_into] = ACTIONS(13),
    [anon_sym_with] = ACTIONS(13),
    [anon_sym_without] = ACTIONS(13),
    [anon_sym_trace] = ACTIONS(15),
    [anon_sym_elapsed] = ACTIONS(15),
    [anon_sym_timeout] = ACTIONS(15),
    [anon_sym_silent] = ACTIONS(15),
    [anon_sym_on] = ACTIONS(15),
    [sym_variable_scalar] = ACTIONS(92),
    [sym_variable_container] = ACTIONS(92),
    [sym_variable_projection] = ACTIONS(94),
    [sym_string] = ACTIONS(92),
    [sym_number] = ACTIONS(92),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_identifier] = ACTIONS(94),
  },
  [STATE(10)] = {
    [anon_sym_DOT] = ACTIONS(96),
    [anon_sym_if] = ACTIONS(98),
    [anon_sym_else] = ACTIONS(98),
    [anon_sym_end] = ACTIONS(98),
    [anon_sym_repeat] = ACTIONS(98),
    [anon_sym_while] = ACTIONS(98),
    [anon_sym_success] = ACTIONS(98),
    [anon_sym_failure] = ACTIONS(98),
    [anon_sym_increase] = ACTIONS(98),
    [anon_sym_decrease] = ACTIONS(98),
    [anon_sym_is] = ACTIONS(98),
    [anon_sym_as] = ACTIONS(98),
    [anon_sym_into] = ACTIONS(98),
    [anon_sym_with] = ACTIONS(98),
    [anon_sym_without] = ACTIONS(98),
    [anon_sym_trace] = ACTIONS(98),
    [anon_sym_elapsed] = ACTIONS(98),
    [anon_sym_timeout] = ACTIONS(98),
    [anon_sym_silent] = ACTIONS(98),
    [anon_sym_on] = ACTIONS(98),
    [sym_variable_scalar] = ACTIONS(96),
    [sym_variable_container] = ACTIONS(96),
    [sym_variable_projection] = ACTIONS(98),
    [sym_string] = ACTIONS(96),
    [sym_number] = ACTIONS(96),
    [anon_sym_true] = ACTIONS(98),
    [anon_sym_false] = ACTIONS(98),
    [sym_identifier] = ACTIONS(98),
  },
  [STATE(11)] = {
    [anon_sym_DOT] = ACTIONS(100),
    [anon_sym_if] = ACTIONS(102),
    [anon_sym_else] = ACTIONS(102),
    [anon_sym_end] = ACTIONS(102),
    [anon_sym_repeat] = ACTIONS(102),
    [anon_sym_while] = ACTIONS(102),
    [anon_sym_success] = ACTIONS(102),
    [anon_sym_failure] = ACTIONS(102),
    [anon_sym_increase] = ACTIONS(102),
    [anon_sym_decrease] = ACTIONS(102),
    [anon_sym_is] = ACTIONS(102),
    [anon_sym_as] = ACTIONS(102),
    [anon_sym_into] = ACTIONS(102),
    [anon_sym_with] = ACTIONS(102),
    [anon_sym_without] = ACTIONS(102),
    [anon_sym_trace] = ACTIONS(102),
    [anon_sym_elapsed] = ACTIONS(102),
    [anon_sym_timeout] = ACTIONS(102),
    [anon_sym_silent] = ACTIONS(102),
    [anon_sym_on] = ACTIONS(102),
    [sym_variable_scalar] = ACTIONS(100),
    [sym_variable_container] = ACTIONS(100),
    [sym_variable_projection] = ACTIONS(102),
    [sym_string] = ACTIONS(100),
    [sym_number] = ACTIONS(100),
    [anon_sym_true] = ACTIONS(102),
    [anon_sym_false] = ACTIONS(102),
    [sym_identifier] = ACTIONS(102),
  },
  [STATE(12)] = {
    [anon_sym_DOT] = ACTIONS(104),
    [anon_sym_if] = ACTIONS(106),
    [anon_sym_else] = ACTIONS(106),
    [anon_sym_end] = ACTIONS(106),
    [anon_sym_repeat] = ACTIONS(106),
    [anon_sym_while] = ACTIONS(106),
    [anon_sym_success] = ACTIONS(106),
    [anon_sym_failure] = ACTIONS(106),
    [anon_sym_increase] = ACTIONS(106),
    [anon_sym_decrease] = ACTIONS(106),
    [anon_sym_is] = ACTIONS(106),
    [anon_sym_as] = ACTIONS(106),
    [anon_sym_into] = ACTIONS(106),
    [anon_sym_with] = ACTIONS(106),
    [anon_sym_without] = ACTIONS(106),
    [anon_sym_trace] = ACTIONS(106),
    [anon_sym_elapsed] = ACTIONS(106),
    [anon_sym_timeout] = ACTIONS(106),
    [anon_sym_silent] = ACTIONS(106),
    [anon_sym_on] = ACTIONS(106),
    [sym_variable_scalar] = ACTIONS(104),
    [sym_variable_container] = ACTIONS(104),
    [sym_variable_projection] = ACTIONS(106),
    [sym_string] = ACTIONS(104),
    [sym_number] = ACTIONS(104),
    [anon_sym_true] = ACTIONS(106),
    [anon_sym_false] = ACTIONS(106),
    [sym_identifier] = ACTIONS(106),
  },
  [STATE(13)] = {
    [anon_sym_DOT] = ACTIONS(108),
    [anon_sym_if] = ACTIONS(110),
    [anon_sym_else] = ACTIONS(110),
    [anon_sym_end] = ACTIONS(110),
    [anon_sym_repeat] = ACTIONS(110),
    [anon_sym_while] = ACTIONS(110),
    [anon_sym_success] = ACTIONS(110),
    [anon_sym_failure] = ACTIONS(110),
    [anon_sym_increase] = ACTIONS(110),
    [anon_sym_decrease] = ACTIONS(110),
    [anon_sym_is] = ACTIONS(110),
    [anon_sym_as] = ACTIONS(110),
    [anon_sym_into] = ACTIONS(110),
    [anon_sym_with] = ACTIONS(110),
    [anon_sym_without] = ACTIONS(110),
    [anon_sym_trace] = ACTIONS(110),
    [anon_sym_elapsed] = ACTIONS(110),
    [anon_sym_timeout] = ACTIONS(110),
    [anon_sym_silent] = ACTIONS(110),
    [anon_sym_on] = ACTIONS(110),
    [sym_variable_scalar] = ACTIONS(108),
    [sym_variable_container] = ACTIONS(108),
    [sym_variable_projection] = ACTIONS(110),
    [sym_string] = ACTIONS(108),
    [sym_number] = ACTIONS(108),
    [anon_sym_true] = ACTIONS(110),
    [anon_sym_false] = ACTIONS(110),
    [sym_identifier] = ACTIONS(110),
  },
  [STATE(14)] = {
    [anon_sym_if] = ACTIONS(112),
    [anon_sym_else] = ACTIONS(112),
    [anon_sym_end] = ACTIONS(112),
    [anon_sym_repeat] = ACTIONS(112),
    [anon_sym_while] = ACTIONS(112),
    [anon_sym_success] = ACTIONS(112),
    [anon_sym_failure] = ACTIONS(112),
    [anon_sym_increase] = ACTIONS(112),
    [anon_sym_decrease] = ACTIONS(112),
    [anon_sym_is] = ACTIONS(112),
    [anon_sym_as] = ACTIONS(112),
    [anon_sym_into] = ACTIONS(112),
    [anon_sym_with] = ACTIONS(112),
    [anon_sym_without] = ACTIONS(112),
    [anon_sym_trace] = ACTIONS(112),
    [anon_sym_elapsed] = ACTIONS(112),
    [anon_sym_timeout] = ACTIONS(112),
    [anon_sym_silent] = ACTIONS(112),
    [anon_sym_on] = ACTIONS(112),
    [sym_variable_scalar] = ACTIONS(114),
    [sym_variable_container] = ACTIONS(114),
    [sym_variable_projection] = ACTIONS(112),
    [sym_string] = ACTIONS(114),
    [sym_number] = ACTIONS(114),
    [anon_sym_true] = ACTIONS(112),
    [anon_sym_false] = ACTIONS(112),
    [sym_identifier] = ACTIONS(112),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(15)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_line, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_line, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_line_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_line_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_line_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_line_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_line_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_line_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_line_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_line, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_line, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_control_keyword, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_control_keyword, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause_keyword, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_clause_keyword, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signature_keyword, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_signature_keyword, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_clause, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_feather(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "feather",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
